### ISSUE TITLE
Reload command broke

### ISSUE THREAD

**Issue by Redstylt** [TastyLollipop/OpenWorld#25]
Version : [ARMX64_SelfContained.zip](https://github.com/TastyLollipop/OpenWorld/releases/download/1.3.8/ARMX64_SelfContained.zip)
System: Pi
Error : 
```
Unhandled exception. System.IO.IOException: The process cannot access the file '/home/mapi/OpenWorldServer1.3.8/Whitelisted Players.txt' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Open_World_Server.ServerUtils.CheckForWhitelistedPlayers()
   at Open_World_Server.MainProgram.ListenForCommands()
   at Open_World_Server.MainProgram.ListenForCommands()
   at Open_World_Server.MainProgram.Main()
Aborted
```
And ofc i wasn't editing any file. I just edited the server settings.txt but it was closed

**Comment by ghost** [comment]
Could you confirm if this keeps happening on a daily basis? Sometimes the OS takes some extra time to close files that have been edited even if they are not visually open anymore.
