### ISSUE TITLE
Allow custom file separators

### ISSUE THREAD

**Issue by kermandev** [TastyLollipop/OpenWorld#4]
Adding Linux dedicated server support will require custom file separators instead of a constant "\\"

**Comment by bertie2** [comment]
having the same issue, specific error message as follows:

```
rimworld@rimworld:~/openworld$ dotnet Open\ World\ Server.dll
[3/5/2022 6:28:19 PM] | Server Startup:
[3/5/2022 6:28:20 PM] | Using Culture Info: [en-US]
[3/5/2022 6:28:20 PM] | Base Directory At: [/home/rimworld/openworld/]
[3/5/2022 6:28:20 PM] | Generating Settings File...
[3/5/2022 6:28:20 PM] | Loading Settings File...
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/rimworld/openworld/Mods/__LocalCopy_Auto-Cut Blight_-5-3/About\About.xml'.
File name: '/home/rimworld/openworld/Mods/__LocalCopy_Auto-Cut Blight_-5-3/About\About.xml'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Open_World_Server.ServerUtils.CheckMods() in D:\Files\Solutions\Open World Server\Open World Server\Utils\ServerUtils.cs:line 162
   at Open_World_Server.ServerUtils.CheckForFiles() in D:\Files\Solutions\Open World Server\Open World Server\Utils\ServerUtils.cs:line 36
   at Open_World_Server.MainProgram.Main() in D:\Files\Solutions\Open World Server\Open World Server\MainProgram.cs:line 62
```

rather than having it be a customizable thing or config setting why not, when combining file paths and loading files, use System.IO.Path.Combine():
https://docs.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=net-6.0
that way it will be platform indipendant?

**Comment by kermandev** [comment]
Yes @bertie2 that would be a better solution, for now you have to hex edit/modify the DLL to use the correct separator

Edit: But this also brings up a few other issues. Why is the mod source not published @TastyLollipop ?

**Comment by ghost** [comment]
Yes, you are right! The server application is not currently set to be able to run in other OS, that's a thing I'm currently working on and will probably be added in next release. Now that bugs have been cleaned up I'm taking more time to upload releases that are more important and packed with stuff. Be sure, support for linux variants is coming soon.

Also yes, the source is not published yet. Not much to it, just personal preference for now. I want to create a stable version of the server / client that runs without problems before posting it, that way It could be easier to identify if bugs were to come from the original fork or variants. In the end is just a way of making me panic less whenever something isn't working correctly.

**Comment by ghost** [comment]
Support for linux is uploaded in newest version. Could you check to confirm 100%? Needs to be further tested

**Comment by kermandev** [comment]
How do you want us to execute on 1.2.0 cause the old method of running the net runtime on the DLL does not work?

**Comment by ghost** [comment]
The new version has a standalone download for Linux now. No need to use the windows dll anymore.

**Comment by bertie2** [comment]
can confirm the linux version seems to be working, Thanks!

**Comment by kermandev** [comment]
seems like it is also working
